// export const drcDepartements = [
//   'PSS',
//   'Protection',
//   'GBV',
//   'MEAL',
//   'MPCA/NFI'
// ]
//
// const jobTitles = [
//   'Coordinator',
//   'Manager',
//   'Team Leader',
//   'Officer',
//   'Assistant',
// ]

export enum DrcJob {
  'Protection Coordinator' = 'Protection Coordinator',
  'Protection Manager' = 'Protection Manager',
  'Protection Team Leader' = 'Protection Team Leader',
  'Protection TL' = 'Protection TL',
  'Protection Officer' = 'Protection Officer',
  'Protection Assistant' = 'Protection Assistant',
  'PSS Coordinator' = 'PSS Coordinator',
  'PSS Manager' = 'PSS Manager',
  'PSS Team Leader' = 'PSS Team Leader',
  'PSS Officer' = 'PSS Officer',
  'PSS Assistant' = 'PSS Assistant',
  'MEAL Coordinator' = 'MEAL Coordinator',
  'MEAL Manager' = 'MEAL Manager',
  'MEAL Team Leader' = 'MEAL Team Leader',
  'MEAL Officer' = 'MEAL Officer',
  'MEAL Assistant' = 'MEAL Assistant',
  'Monitoring, Evaluation, Accountability and Learning Officer' = 'Monitoring, Evaluation, Accountability and Learning Officer',
  'Monitoring, Evaluation, Accountability and Learning Specialist' = 'Monitoring, Evaluation, Accountability and Learning Specialist',
  'MPCA/NFI Coordinator' = 'MPCA/NFI Coordinator',
  'MPCA/NFI Manager' = 'MPCA/NFI Manager',
  'MPCA/NFI Team Leader' = 'MPCA/NFI Team Leader',
  'MPCA/NFI Officer' = 'MPCA/NFI Officer',
  'MPCA/NFI Assistant' = 'MPCA/NFI Assistant',
  'MPCA Assistant' = 'MPCA Assistant',
  'Cash And Voucher Assistance Officer' = 'Cash And Voucher Assistance Officer',
  'Distribution TL' = 'Distribution TL',
  'NFI Assistant' = 'NFI Assistant',
  'GBV Coordinator' = 'GBV Coordinator',
  'GBV Manager' = 'GBV Manager',
  'GBV Team Leader' = 'GBV Team Leader',
  'GBV Officer' = 'GBV Officer',
  'GBV Assistant' = 'GBV Assistant',
  'Shelter and Settlement Manager' = 'Shelter and Settlement Manager',
  'Shelter Assistant' = 'Shelter Assistant',
  'Shelter and Settlement specialist' = 'Shelter and Settlement specialist',
  'Area Manager' = 'Area Manager',
  'Base Manager' = 'Base Manager',
  'Partnership Manager' = 'Partnership Manager',
  'Capacity Building Programme Manager' = 'Capacity Building Programme Manager',
  'Global Roving Advisor' = 'Global Roving Advisor',
  'Gender Based Violence Specialist' = 'Gender Based Violence Specialist',
  'Shelter Officer' = 'Shelter Officer',
  'Shelter and Settlement Team Leader' = 'Shelter and Settlement Team Leader',
  'Cash and Voucher Assistance Manager' = 'Cash and Voucher Assistance Manager',
  'Economic Recovery Officer' = 'Economic Recovery Officer',
  'Accountant' = 'Accountant',
  'Programme Officer' = 'Programme Officer',
}

export enum DrcOffice {
  Kyiv = 'Kyiv',
  Sumy = 'Sumy',
  Mykolaiv = 'Mykolaiv',
  Lviv = 'Lviv',
  Chernihiv = 'Chernihiv',
  Kharkiv = 'Kharkiv',
  Dnipro = 'Dnipro',
}